In [1]:
import pandas as pd

# Specify the path to your CSV file including the file name
file_path = r'C:\Users\jackf\OneDrive\Desktop\Bike_Sharing\UCI_Bike_Sharing\data\day.csv'

# Read the CSV file into a DataFrame
day_Bike = pd.read_csv(file_path)

# Display the DataFrame
day_Bike

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,331,654,985
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,131,670,801
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,120,1229,1349
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,108,1454,1562
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,82,1518,1600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,727,2012-12-27,1,1,12,0,4,1,2,0.254167,0.226642,0.652917,0.350133,247,1867,2114
727,728,2012-12-28,1,1,12,0,5,1,2,0.253333,0.255046,0.590000,0.155471,644,2451,3095
728,729,2012-12-29,1,1,12,0,6,0,2,0.253333,0.242400,0.752917,0.124383,159,1182,1341
729,730,2012-12-30,1,1,12,0,0,0,1,0.255833,0.231700,0.483333,0.350754,364,1432,1796
730,731,2012-12-31,1,1,12,0,1,1,2,0.215833,0.223487,0.577500,0.154846,439,2290,2729

In [5]:
import pandas as pd
import statsmodels.api as sm
from statsmodels.tsa.arima.model import ARIMA

# Assuming your date_Bike dataframe has a datetime index
day_Bike['dteday'] = pd.to_datetime(day_Bike['dteday'])
day_Bike.set_index('dteday', inplace=True)

# Replace 'your_column' with the column you want to predict (e.g., 'cnt')
y = day_Bike['cnt']

# Fit ARIMA model
arima_model = ARIMA(y, order = (5, 1, 0))  # Example order, you may need to tune this
arima_result = arima_model.fit()

# Forecast future values
future_steps = 30  # Adjust as needed
forecast = arima_result.get_forecast(steps = future_steps)

# Print the forecasted values
(forecast.predicted_mean)

C:\Users\jackf\anaconda3\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
C:\Users\jackf\anaconda3\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
C:\Users\jackf\anaconda3\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)

2013-01-01    2085.026056
2013-01-02    2174.025046
2013-01-03    2289.020528
2013-01-04    2057.877658
2013-01-05    2087.776140
2013-01-06    2231.349366
2013-01-07    2179.724878
2013-01-08    2180.821824
2013-01-09    2189.451815
2013-01-10    2154.891201
2013-01-11    2153.154758
2013-01-12    2174.959020
2013-01-13    2174.545152
2013-01-14    2175.010642
2013-01-15    2174.953722
2013-01-16    2168.939144
2013-01-17    2167.313520
2013-01-18    2170.443220
2013-01-19    2171.611506
2013-01-20    2172.145478
2013-01-21    2172.045395
2013-01-22    2170.895368
2013-01-23    2170.314471
2013-01-24    2170.686979
2013-01-25    2171.059918
2013-01-26    2171.292653
2013-01-27    2171.309385
2013-01-28    2171.089774
2013-01-29    2170.921585
2013-01-30    2170.938652
Freq: D, Name: predicted_mean, dtype: float64

In [8]:
import pandas as pd
import statsmodels.api as sm
from statsmodels.tsa.arima.model import ARIMA

# Assuming your date_Bike dataframe has a datetime index
day_Bike['dteday'] = pd.to_datetime(day_Bike['dteday'])
day_Bike.set_index('dteday', inplace=True)

# Replace 'your_column' with the column you want to predict (e.g., 'cnt')
y = day_Bike['cnt']

# Fit ARIMA model
arima_model = ARIMA(y, order=(5, 1, 0))  # Example order, you may need to tune this
arima_result = arima_model.fit()

# Forecast future values for the year 2100
future_steps = 365 * (2100 - 2013)  # Assuming a daily frequency
future_dates = pd.date_range(start='2013-01-01', periods=future_steps)
forecast = arima_result.get_forecast(steps=future_steps)

# Create a new DataFrame for the forecasted values
forecast_df = pd.DataFrame(forecast.predicted_mean, index=future_dates, columns=['predicted_mean'])

# Print or use the forecasted values
print(forecast_df)

C:\Users\jackf\anaconda3\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
C:\Users\jackf\anaconda3\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
C:\Users\jackf\anaconda3\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)

            predicted_mean
2013-01-01     2085.026056
2013-01-02     2174.025046
2013-01-03     2289.020528
2013-01-04     2057.877658
2013-01-05     2087.776140
...                    ...
2099-12-06     2171.052334
2099-12-07     2171.052334
2099-12-08     2171.052334
2099-12-09     2171.052334
2099-12-10     2171.052334

[31755 rows x 1 columns]

In [11]:
import pandas as pd
import statsmodels.api as sm
from statsmodels.tsa.arima.model import ARIMA

# Assuming your date_Bike dataframe has a datetime index
day_Bike['dteday'] = pd.to_datetime(day_Bike['dteday'])
day_Bike.set_index('dteday', inplace=True)

# Replace 'your_column' with the column you want to predict (e.g., 'cnt')
y = day_Bike['cnt']

# Fit ARIMA model
arima_model = ARIMA(y, order=(5, 1, 0))  # Example order, you may need to tune this
arima_result = arima_model.fit()

# Forecast future values for the year 2100
future_steps = 365 * (2100 - 2013)  # Assuming a daily frequency
future_dates = pd.date_range(start='2013-01-01', periods=future_steps)
forecast = arima_result.get_forecast(steps=future_steps)

# Add forecasted values to a new DataFrame
forecast_df = pd.DataFrame(index=future_dates)
forecast_df['predicted_mean'] = forecast.predicted_mean

# Access the forecasted value for January 5, 2100
specific_date = pd.to_datetime('2099-01-05')
forecast_value = forecast_df.loc[specific_date, 'predicted_mean']

# Print or use the forecasted value
print(f'Predicted value for 2100-01-05: {forecast_value:.2f}')

C:\Users\jackf\anaconda3\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
C:\Users\jackf\anaconda3\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)
C:\Users\jackf\anaconda3\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  self._init_dates(dates, freq)

Predicted value for 2100-01-05: 2171.05